-
    name: "Install and configure LAMP"
    hosts: lamp
    become: yes
    tasks:
      -
        name: "Install firewalld, git and MySQL-python"
        yum:
          name:
          - firewalld
          - git
          - MySQL-python
      -
        name: "Start and enable firewalld service"
        service:
          name: firewalld
          state: started
          enabled: yes
      -
        name: "Install MariaDB"
        yum:
          name: mariadb-server
      -
        name: "Start and enable MariaDB service"
        service:
          name: mariadb
          state: started
          enabled: yes
      -
        name: "Configure MySQL port on firewalld"
        firewalld:
          port: 3306/tcp
          permanent: yes
          zone: public
          state: enabled
          immediate: yes
      -
        name: "Create database"
        mysql_db:
          name: ecomdb
          state: present
      -
        name: "Create a database user"
        mysql_user:
          name: ecomuser
          password: ecompassword
          state: present
          priv: '*.*:ALL'
      -
        name: "Download site code"
        git:
          repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
          dest: /home/vagrant/learning-app-ecommerce
      -
        name: "Load product inventory to database"
        mysql_db:
          login_user: ecomuser
          login_password: ecompassword
          state: import
          name: all
          target: /home/vagrant/learning-app-ecommerce/assets/db-load-script.sql
      -
        name: "Install web required packages"
        yum:
          name:
            - httpd
            - php
            - php-mysql
      -
        name: "Configure HTTP port on firewalld"
        firewalld:
            port: 80/tcp
            permanent: yes
            zone: public
            state: enabled
            immediate: yes
      -
        name: "Configure httpd"
        replace:
          path: /etc/httpd/conf/httpd.conf
          regexp: 'index.html'
          replace: "index.php"
      -
        name: "Copy site code to the right path"
        copy:
          src: /home/vagrant/learning-app-ecommerce/
          dest: /var/www/html
          remote_src: yes
      -
        name: "Update index.php"
        replace:
          path: /var/www/html/index.php
          regexp: '172.20.1.101'
          replace: "localhost"
      -
        name: "Start and enable httpd service"
        service:
          name: httpd
          state: started
          enabled: yes
      -
        name: "Test"
        uri:
          url: http://192.168.1.51
